source: pincher_gripper.yaml
model:  parallel
center: 0
scale: 1
joint: gripper_link_joint
# The following is only for the custom servo used in turtlebot_arm
pad_width: 0.002
min_opening: 0.002
max_opening: 0.031
neutral: 0.015
tighten: .001

